### ISSUE TITLE
Introduce Tagging custom objects

### ISSUE THREAD

**Issue by ppp0** [cargomedia/bipbip#102]
In order to effectively mute alerts during maintenance windows we need to be able to tag the objects we programmatically create with bipbip

Analogous to what we do with copperegg-revealcloud ?

**Comment by njam** [comment]
I guess this should be configurable for the whole bipbip instance, and overrideable per service plugin.

**Comment by njam** [comment]
After some testing I can confirm that *server* tags and *custom metrics* tags work well together. While we need to create both tags individually, we can mute them together if they have the same name.

I'm looking into how to best use the custom metrics tag API now (http://dev.copperegg.com/revealmetrics/tags.html).

**Comment by njam** [comment]
I opened a pull request on the copperegg client gem: https://github.com/CopperEgg/copperegg-ruby/pull/6

**Comment by njam** [comment]
Custom object tagging is working.

Unfortunately "alert cleared" still issues a notification (although the original alert was muted). I inquired about it with Copperegg...
