### ISSUE TITLE
Plugin stuck

### ISSUE THREAD

**Issue by njam** [cargomedia/bipbip#114]
Just experienced a "stuck" bipbip "command" running `pulsar`.
When I killed the `pulsar` process the bipbip plugin continued running and collecting data.

Maybe we should add a plugin run timeout either in `Agent.run()` or `Plugin.run()`.

**Comment by njam** [comment]
I experienced many "stuck" bipbip processes today. Usually all plugin processes would *not* send data. I tried closing some file descriptors manually (using `gdb`) but no luck. Sending `TERM` to an individual plugin process would make it exit, then the parent respawns the plugin, and it successfully collects data.

Such cases should be solved as well by introducing a timeout in `Plugin.run()`.

**Comment by njam** [comment]
Version 0.6 (with timeout and threading) deployed as of: 2015-04-21

**Comment by njam** [comment]
Another bipbip instance stuck: `config3.mongodb.fuckbook.com` didn't send any more data after `2015-04-23 6:27 UTC`.

Last bipbip log entry:
```
W, [2015-04-23T06:25:09.366093 #1793]  WARN -- log-parser config3.mongodb.fuckbook.com::logparser-syslog::_var_log_syslog: File event `move_self` detected, resetting notifier
```

Syslog:
```
2015-04-23T06:19:53.210524+00:00 config3 puppet-agent[10502]: Finished catalog run in 9.95 seconds
2015-04-23T06:25:02.854821+00:00 config3 rsyslogd: [origin software="rsyslogd" swVersion="5.8.11" x-pid="3116" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
2015-04-23T06:29:52.580501+00:00 config3 puppet-agent[12979]: Finished catalog run in 9.71 seconds
```
It seems it's stopping to work after log rotation time:
```
-rw-r--r--  1 bipbip bipbip  175 Apr 24 06:25 bipbip.log.1
-rw-r--r--  1 bipbip bipbip  167 Apr 23 06:25 bipbip.log.2.gz
```

The stuck process doesn't respond to a `TERM` signal. Attaching `strace` shows:
```
futex(0x1e3f054, FUTEX_WAIT_PRIVATE, 215144, NULL
```

I'm now suspecting it's related to bipbip's own log being rotated (combined with some other factor?).

**Comment by njam** [comment]
Another occasion: `rep1-db4.mongodb.fuckbook.com` got stuck at `2015-04-26 6:26 UTC`.

Bipbip log:
```
W, [2015-04-26T06:25:18.549064 #21001]  WARN -- log-parser rep1-db4.mongodb.fuckbook.com::logparser-syslog::_var_log_syslog: File event `move_self` detected, resetting notifier
```

Again, this is log rotation time - for both bipbip and syslog:
```
-rw-r--r--  1 bipbip bipbip  170 Apr 26 06:25 bipbip.log.2.gz
-rw-r--r-- 1 root root  3109 Apr 26 06:25 /var/log/syslog.5.gz
```

To verify that the logparser plugin is causing these problems I'd suggest to disable bipbip logrotation temporarily.
-> https://github.com/cargomedia/puppet-packages/pull/892

**Comment by njam** [comment]
Disabled bipbip log rotation as of: 2015-04-30

**Comment by njam** [comment]
All nodes still reporting

**Comment by njam** [comment]
Another occasion: `config1.mongodb.fuckbook.com` got stuck at `2015-05-15 6:26 UTC`.

Bipbip log:
```
E, [2015-05-15T05:50:32.967652 #20197] ERROR -- log-parser config1.mongodb.fuckbook.com::logparser-syslog::_var_log_syslog: Measurement timeout of 30.0 seconds reached.
W, [2015-05-15T06:25:04.568140 #20197]  WARN -- log-parser config1.mongodb.fuckbook.com::logparser-syslog::_var_log_syslog: File event `move_self` detected, resetting notifier
```

Bipbip's log rotation was disabled! So it's definitely the logrotation that somehow makes the logparser plugin trip:
```
2015-05-15T06:25:03.168785+00:00 config1 rsyslogd: [origin software="rsyslogd" swVersion="5.8.11" x-pid="2999" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
```

**Comment by njam** [comment]
I tried to reproduce this issue extensively. What I found:
- Cannot reproduce in a VirtualBox VM
- Can rarely reproduce on a SoftLayer VM

To reproduce I had to:
- Use the normal bipbip instance on the machine
- Use log-parser on syslog
- Rotate syslog every second (`logrotate -fv /etc/logrotate.d/rsyslog`)
- Then *sometimes* the plugin gets stuck!

**Comment by njam** [comment]
I have a stacktrace via `gdb`:
```
	from /tmp/reto-bipbip/bipbip/lib/bipbip/agent.rb:81:in `block in start_plugin'
	from /tmp/reto-bipbip/bipbip/lib/bipbip/plugin.rb:41:in `run'
	from /usr/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
	from /tmp/reto-bipbip/bipbip/lib/bipbip/plugin.rb:42:in `block in run'
	from /tmp/reto-bipbip/bipbip/lib/bipbip/plugin.rb:95:in `run_measurement'
	from /tmp/reto-bipbip/bipbip/lib/bipbip/plugin.rb:95:in `each'
	from /tmp/reto-bipbip/bipbip/lib/bipbip/plugin.rb:96:in `block in run_measurement'
	from /tmp/reto-bipbip/bipbip/lib/bipbip/storage/copperegg.rb:61:in `store_sample'
	from /var/lib/gems/1.9.1/gems/copperegg-revealmetrics-0.8.1/lib/copperegg/revealmetrics/metric_sample.rb:10:in `save'
	from /var/lib/gems/1.9.1/gems/copperegg-revealmetrics-0.8.1/lib/copperegg/revealmetrics/mixins/persistence.rb:58:in `request'
	from /usr/lib/ruby/1.9.1/net/http.rb:1284:in `request'
	from /usr/lib/ruby/1.9.1/net/http.rb:745:in `start'
	from /usr/lib/ruby/1.9.1/net/http.rb:1286:in `block in request'
	from /usr/lib/ruby/1.9.1/net/http.rb:1293:in `request'
	from /usr/lib/ruby/1.9.1/net/http.rb:1315:in `transport_request'
	from /usr/lib/ruby/1.9.1/net/http.rb:1330:in `rescue in transport_request'
	from /usr/lib/ruby/1.9.1/net/protocol.rb:76:in `close'
	from /usr/lib/ruby/1.9.1/openssl/buffering.rb:447:in `close'
	from /usr/lib/ruby/1.9.1/openssl/buffering.rb:447:in `sysclose'
```
Code in question is:
```rb
    def transport_request(req)
      begin_transport req
      res = catch(:response) {
        req.exec @socket, @curr_http_version, edit_path(req.path)
        begin
          res = HTTPResponse.read_new(@socket)
        end while res.kind_of?(HTTPContinue)
        res.reading_body(@socket, req.response_body_permitted?) {
          yield res if block_given?
        }
        res
      }
      end_transport req, res
      res
    rescue => exception
      D "Conn close because of error #{exception}"
      @socket.close if @socket and not @socket.closed?
      raise exception
    end
```
(`begin_transport` fails, then the `close` in the rescue-block gets stuck)

**Comment by njam** [comment]
Mongo plugin with new client released as of: 2015-06-19

**Comment by njam** [comment]
We have two instances of stuck plugins today. I think this might still be from releasing the mongodb client upgrade. At least one of them didn't restart:
- search2: 2015-06-22 19:00
- stream2: 2015-06-23 5:00

I'm restarting all instances now and make sure they run as desired.
Then I'll keep an eye on it..

**Comment by ppp0** [comment]
Observing stuck behaviour, too..

I did a `monit restart` and `tailf /var/log/bipbip/bipbip.log`:

```
I, [2015-06-24T14:33:21.781680 #28942]  INFO -- : Received signal TERM, interrupting...
I, [2015-06-24T14:33:41.785327 #28942]  INFO -- : Received signal TERM, interrupting...
```

(Log excerpt above is from Jul 2nd on www5! This means to me that bipbip waits since a week to be TERM'd - Log has even been rotated in the meanwhile!)

`kill -9` helps

**Comment by njam** [comment]
Bipbip stuck on `pulsar1` at `2015-06-24 16:30`.
Same here - bipbip received a `TERM` signal on June 24th and is stuck since:
```
I, [2015-06-24T14:30:49.694601 #16914]  INFO -- : Received signal TERM, interrupting...
I, [2015-06-24T14:31:09.713136 #16914]  INFO -- : Received signal TERM, interrupting...
```

**Comment by njam** [comment]
Bipbip 0.6.4 released on all servers as of: 2015-07-06

**Comment by njam** [comment]
All servers still reporting as of: 2015-05-16

**Comment by njam** [comment]
Restart due to upgrade: 2015-07-21

All servers still reporting as of: 2015-07-23

**Comment by njam** [comment]
All servers still reporting as of: 2015-07-27

**Comment by njam** [comment]
All servers still reporting as of: 2015-08-14

I think we can consider this fixed!
