### ISSUE TITLE
Investigate: plugin for NewRelic

### ISSUE THREAD

**Issue by ppp0** [cargomedia/bipbip#122]
Needed:

- [ ] Arbitrarily create metrics
- [ ] Metric Groups
- [x] Dashboards
- [x] Alerts to Pagerduty, SMS, Email, Hipchat
- [ ] Muting of alerts
- [ ] ... ?

**Comment by kris-lab** [comment]
It would be `storage` of type 'Newrelic`:
- [ ] custom objects
- [ ] verify metrics params (types, units)
- [ ] verify alerts rules
- [ ] ...

**Comment by ppp0** [comment]
hmhm
https://docs.newrelic.com/docs/alerts/new-relic-alerts-beta/getting-started/known-limitations-new-relic-alerts

**Comment by kris-lab** [comment]
hmm quite problematic issues...

**Comment by njam** [comment]
Closing. Let's reopen if we need another tool.
