### ISSUE TITLE
Mongo: collect slow query metrics

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/bipbip#92]
The idea is to track slow queries for each db instance. See [docu](http://docs.mongodb.org/manual/reference/command/profile/?_ga=1.53773996.500742327.1415094953)

Something like:
```
db.system.profile.find({$where: ts > [last-check]}).count()
```

Make sure to set "slaveOk"!

**Comment by njam** [comment]
I understand we should enable the profiler on the infrastructure (puppet) level, configure a threshold in milliseconds, and then in this plugin read the *number of slow queries* from the profiler.

Example: [script for scout](https://raw.githubusercontent.com/scoutapp/scout-plugins/master/mongo_slow_queries/mongo_slow_queries.rb)

**Comment by kris-lab** [comment]
yes, correct!
